name: Sonarqube scanner
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: fetching
        if: contains(github.ref, 'pull')
        run: |
          git fetch origin ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: SonarQube Scan
        uses: tradeshift/actions-sonarqube@v2
        with:
          args: -Dsonar.java.binaries=target/classes
          ca-cert: ${{ secrets.MTLS_CACERT }}
          client-cert: ${{ secrets.MTLS_CERT }}
          client-key: ${{ secrets.MTLS_KEY }}
          token: ${{ secrets.SONAR_TOKEN }}
          host: 'https://sonar.ts.sv'
